# frozen_string_literal: true

source 'https://rubygems.org'

gem 'docker-api'
gem 'git'
gem 'nokogiri'
gem 'os'
gem 'rake'
gem 'rake_docker'
gem 'rake_factory'
gem 'rake_git'
gem 'rake_git_crypt'
gem 'rake_github'
gem 'rake_gpg'
gem 'rake_slack'
gem 'rake_terraform'
gem 'rspec'
gem 'rubocop'
gem 'rubocop-rake'
gem 'rubocop-rspec'
gem 'semantic'
gem 'serverspec'
